services:
  api:
    build: .
    ports:
      - 8080:8080
      # volumes
    env_file: ".env"
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine3.22
    env_file: ".env.postgres"
    ports:
      - 5432:5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
