services:
  api:
    build: .
    ports:
      - 8080:8080
      # volumes
    env_file: ".env"
    environment:
      DB_URL: "postgres://app:test@db/subscriptions"
      PORT: 8080
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: app
      POSTGRES_DB: subscriptions
